#!/bin/bash
set -euo pipefail

SITE_DIR="${1:-_site}"

mkdir -p "$SITE_DIR/rebase-dag" "$SITE_DIR/rebase-dashboard"

# Prow audit page
if [ -f tools/prow-merge-bot-configs/index.html ]; then
  cp tools/prow-merge-bot-configs/index.html "$SITE_DIR/"
fi

# Prow audit badge (generated by prow-audit-status workflow)
if [ -f /tmp/badge.json ]; then
  cp /tmp/badge.json "$SITE_DIR/"
fi

# Rebase DAG page (Cytoscape.js graph)
cp tools/rebase-dag/index.html "$SITE_DIR/rebase-dag/"
cp tools/rebase-dag/dag-data.js "$SITE_DIR/rebase-dag/"

# Rebase Dashboard (React app — built by CI before this script runs)
if [ -d tools/rebase-dashboard/dist ]; then
  cp -r tools/rebase-dashboard/dist/* "$SITE_DIR/rebase-dashboard/"
fi

# DAG data (generated by rebase-status-wiki workflow)
# Shared by both the DAG and Dashboard pages.
if ls /tmp/dag-data/*.json >/dev/null 2>&1; then
  for f in /tmp/dag-data/*.json; do
    cp "$f" "$SITE_DIR/rebase-dag/dag-$(basename "$f")"
    cp "$f" "$SITE_DIR/rebase-dashboard/dag-$(basename "$f")"
  done
fi

echo "Assembled Pages site in $SITE_DIR:"
find "$SITE_DIR" -type f | sort | sed 's/^/  /'
