#!/bin/bash
set -euo pipefail

SITE_DIR="${1:-_site}"

mkdir -p "$SITE_DIR/rebase-dag/data"

# Prow audit page
if [ -f tools/prow-merge-bot-configs/index.html ]; then
  cp tools/prow-merge-bot-configs/index.html "$SITE_DIR/"
fi

# Prow audit badge (generated by prow-audit-status workflow)
if [ -f /tmp/badge.json ]; then
  cp /tmp/badge.json "$SITE_DIR/"
fi

# Rebase DAG page
cp tools/rebase-dag/index.html "$SITE_DIR/rebase-dag/"
cp tools/rebase-dag/dag-data.js "$SITE_DIR/rebase-dag/"

# DAG data (generated by rebase-status-wiki workflow)
if ls /tmp/dag-data/*.json >/dev/null 2>&1; then
  cp /tmp/dag-data/*.json "$SITE_DIR/rebase-dag/data/"
fi

echo "Assembled Pages site in $SITE_DIR:"
find "$SITE_DIR" -type f | sort | sed 's/^/  /'
