import { useDAGData } from './hooks/useDAGData'
import { Header } from './components/Header'
import { SummaryBar } from './components/SummaryBar'
import { DAGCanvas } from './components/DAGCanvas'
import { Legend } from './components/Legend'
import { colors } from './styles/theme'

export default function App() {
  const { metadata, repos, cvePRs, branch, loading, setBranch } = useDAGData()

  return (
    <>
      <Header metadata={metadata} branch={branch} onBranchChange={setBranch} />
      <SummaryBar repos={repos} branch={branch} loading={loading} generatedAt={metadata?.generated_at} />

      {loading ? (
        <div style={{
          flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
          color: colors.muted, fontSize: '1rem',
        }}>
          Loading...
        </div>
      ) : repos.length === 0 ? (
        <div style={{
          flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
          flexDirection: 'column', gap: '.5rem', color: colors.muted, fontSize: '1rem',
        }}>
          <div>No data available{branch ? ` for ${branch}` : ''}</div>
          <div style={{ fontSize: '.8rem' }}>Data is generated by the Rebase Status Wiki workflow</div>
        </div>
      ) : (
        <DAGCanvas repos={repos} cvePRs={cvePRs} />
      )}

      <Legend />
    </>
  )
}
